# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-31 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndicationsForUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_information', models.TextField(null=True)),
                ('for_children', models.TextField()),
                ('for_elderly_people', models.TextField()),
                ('for_pregnant_women', models.TextField()),
                ('for_lactating_mothers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('registration_number', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('composition', models.TextField()),
                ('description', models.TextField()),
                ('code_ATH', models.TextField(unique=True)),
                ('pharmacodynemics', models.TextField(null=True)),
                ('contra', models.TextField()),
                ('carefully', models.TextField()),
                ('use_for_pregnancy_lactating', models.TextField()),
                ('dosing', models.TextField()),
                ('extra_effects', models.TextField()),
                ('overdose', models.TextField(null=True)),
                ('with_other_drugs', models.TextField(null=True)),
                ('special_instructions', models.TextField()),
                ('form_edition', models.TextField()),
                ('conditions_saving', models.TextField()),
                ('experation_date', models.TextField(max_length=30)),
                ('owner_of_registration_number', models.TextField()),
                ('manufacturer', models.TextField()),
                ('barcode', models.IntegerField()),
                ('drug_form', models.ManyToManyField(to='pharm.DrugForm')),
                ('indication_for_use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.IndicationsForUse')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacokinetics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_information', models.TextField()),
                ('absorption', models.TextField()),
                ('distribution', models.TextField()),
                ('metabolism', models.TextField()),
                ('breeding', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PharmacotherapeuticGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='manual',
            name='pharmacokinetics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharm.Pharmacokinetics'),
        ),
        migrations.AddField(
            model_name='manual',
            name='pharmacotherapeutic_group',
            field=models.ManyToManyField(to='pharm.PharmacotherapeuticGroup'),
        ),
        migrations.AddField(
            model_name='manual',
            name='pharmacy_conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.PharmacyConditions'),
        ),
    ]
