# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-31 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='barcode',
            field=models.TextField(),
        ),
    ]
